export const TRAITS = [
  "Leadership",
  "Creativity",
  "Analytical Thinking",
  "Problem Solving",
  "Empathy",
  "Adaptability",
  "Communication",
  "Collaboration",
  "Initiative",
  "Discipline",
  "Integrity",
  "Vision",
  "Resilience",
  "Curiosity",
  "Strategic Thinking",
  "Detail Orientation",
  "Time Management",
  "Coaching",
  "Decision Making",
  "Innovation",
  "Accountability",
  "Customer Focus",
  "Learning Agility",
  "Emotional Intelligence",
  "Negotiation",
  "Conflict Resolution",
  "Ownership",
  "Planning",
  "Process Improvement",
  "Quality Mindset",
  "Risk Management",
  "Data Literacy",
  "Systems Thinking",
  "Entrepreneurship",
  "Service Orientation",
  "Public Speaking",
  "Writing",
  "Design Sense",
  "Product Sense",
  "User Research",
  "Sales Acumen",
  "Financial Acumen",
  "Technical Aptitude",
  "Cybersecurity Awareness",
  "Project Management",
  "Change Management",
  "Mentorship",
  "Networking",
  "Cultural Awareness",
  "Ethics"
];
